### ISSUE TITLE
Week #8 Midterm ready for grading

### ISSUE THREAD

**Issue by bhurda** [madisoncollege-it-programs/python-scripting-bhurda#10]

**Comment by cethenmc** [comment]
- Midterm-if:  I like the creativity of using a concept we did not learn in this class yet by this point.  I assume you could not recall a method to extract the line number as requested.  As a result of not extracting the line number and converting it to an int (which was a hint to help you know what you might use to extract), you will have a 4 pt deduction.  The function repeated unnecessarily for each search string made the code fairly noisy (1 pt).  Additionally, a specified requirement was to use elifs with your if (2 pts)  Finally, you did not close the file when you did not open it in a "with" block (1 pt).  Your total score is 25/33.  

- Midterm-jpark:  Thanks for putting in an effort on this part of the midterm.  The first part I analyze is program execution.  When I execute, your name is not the first thing to print on my screen (1 pt).  Then there is a never-ending request for user_name, so no access possible (8 pts).  Next I evaluate the code.  It looked like you did have a print of your name, but then made it a comment.  You were required to have an Author and Description comment at the top (1 pt).  Nice job establishing your dictionaries.  You left a print of a counter in the code, but since that showed up where the name was supposed to print, I already took a 1 off and won't from the code.  The while loop has an immediate break and a commented out line multiplying the string by 25 to show me you understand that concept, but it is a while loop that does nothing (2 pts).  The username and password should be evaluated together (2 pts).  Concepts of input are grasped well, in that you know you need to set to a variable, but the print of the command choices should pull directly from the dictionary's keys (2 pts).  The flow logic out of the command entered can be evaluated directly against the dictionary, as well, with the use of the input variable for lookup, instead of hardcoding the values (2 pts).  Score 15/33.

- Midterm-slicing:  Thanks for putting in an effort on this part of the midterm.  Author and description were not added to the file (1 pt).  It looks like you were able to get a lot of the slicing, but did not save any of them to a variable like the activity required (5 pts).  Letter 'd' in the slicing was off by a digit (1 pt).  After the slicing, it would have been difficult to join your results together with variables.  It looks like you were making some effort in pasting the data into lists and working a join.  However, the join was by the new line feed which did not exist in your lists (5 pts).  Lastly, you did not close your file (1 pt)      21/34
