### ISSUE TITLE
Week# 7 Ready for grading.

### ISSUE THREAD

**Issue by bhurda** [madisoncollege-it-programs/python-scripting-bhurda#9]

**Comment by cethenmc** [comment]
Hi, Brett.  I appreciate your creativity to get answers on this lab.  Since you made the creative effort, I will start you with a 5 out of 8 for now.  **However, I highly recommend you book time with me on this lab: 30 minutes.**  If the times in Blackboard don't work for you, email me another time.  I am concerned with all of your backed up corrections on previous labs that you either are not checking your Madison College email, or you just are not getting time, which could be concerning for the MidTerm that is due Thursday.

There is an easier way than what you chose to do.  You got many of the answers, but you did so by creating redundant nested dictionaries.  The intention of # 2, 3, and 4 were to use three new functions you learned in the lesson (though it did not explicitly say that).  The reason # 5 was after 2, 3, & 4, was because we want to see that you can add to an existing and established dictionary (outside of the initial creation).  # 6 you are printing the same clause in the if and the else, giving you a false impression that what you did for that one would work.  Change your else-statement in # 7 to "isn't" and rerun your script.

Please take another look, and also book some time with me.

Thanks.

Chris

**Comment by cethenmc** [comment]
Locking in grade and closing ticket.
